---
title       : The Amazing Zorbax!
subtitle    : Predicts your Ultimate Outcome
author      : S Duffy
job         : 
framework   : io2012   # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## The Pitch

Humans are obsessed with dying, afraid of when death will come knock at their door.  

Now there is The Amazing Zorbax!  

It's an app that, with a few basic inputs, will tell people how many years they have left to live.

--- .class #id 

## App Description

The app is quite simple:

Enter your age, race, and gender

and the Amazing Zorbax app returns how many years you have remaining in your life!


---

## Background

The app uses data from the US Centers for Disease Control and Prevention

The CDC publishes the National Vital Statics Reports, which have life expectancy tables.

This app uses data from the National Vital Statistics Reports, Vol. 64 No. 2, February 16, 2016.

Found at  
http://www.cdc.gov/nchs/data/nvsr/nvsr64/nvsr64_02.pdf  
and accessed June 17, 2016.


---

## Data Basis

This is a partial view of the data used in this app. It excludes lines by gender for the sake
of clarity.

``` {r plot, echo=FALSE}
Death <-  read.csv("Death.csv")
plot(Death$Age,Death$All_Both,"l", col="red", lwd = 5, main= "General Population Life Expectancy in the USA", xlab = "Age Now", ylab = "Years Remaing")
lines(Death$White_Both, col="blue", lwd = 2,lty=4)
lines(Death$Black_Both, col = "black", lwd = 2,lty=4)
lines(Death$Hispanic_Both,col = "brown", lwd = 2,lty=4)
legend(75,80, c("All","White","Black","Hispanic"), lty=c(1,4,4,4), lwd=c(4,2,2,2),col=c("red","blue","black","brown"))
```

